name: Deploy Charity Backend (Staging)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: staging

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install PM2 globally
      - name: Install PM2
        run: npm install -g pm2

      # 4. Install project dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Start / Restart the app using PM2
      - name: Start / Restart App with PM2
        run: |
          APP_NAME="stage_charity_app_backend"
          if pm2 info "$APP_NAME" >/dev/null 2>&1; then
            pm2 stop "$APP_NAME"
            pm2 start "$APP_NAME"
            pm2 save
          else
            pm2 start src/server.js --name "$APP_NAME"
          fi
