name: my first ever job

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message 
          run: echo "My first Github Actions Job"

        - name: List files 
          run: ls

        - name: Git Clone Repository
          run: git clone https://github.com/Rayu-tech/solar-system.git

        - name: change directory 
          run: cd "solar-system"

        - name: List all files 
          run: ls -al

        - name: Read files
          run: cat README.md


