name: Generate ASCII Artwork

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Convert line endings (fix Windows CRLF issue)
        run: sudo apt-get install -y dos2unix && dos2unix ascii-script.sh

      - name: Executing Ascii shell script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
